### ISSUE TITLE
Testing this lidar using the ESP32-E Firebeetle 2

### ISSUE THREAD

**Issue by Nacros115** [jpiat/cspc-lidar-coin-d4#1]
Hello,

I try converting your code for the esp32, because I don't have a rasberry pi, but I cannot find a way to make it work, the lidar show a blue led, when I use rx and tx on my board, I can't see anything, here is the code I've used so far :
```
#include <Arduino.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <WiFi.h>
#include <WebSocketsServer_Generic.h>

// WiFi Access Point Configuration
#define AP_SSID     "ESP32-LIDAR"
#define AP_PASSWORD "12345678"  // At least 8 characters

WiFiServer server(80);
WebSocketsServer webSocket = WebSocketsServer(81);

#define SCAN_DATA_LENGTH (512 * 3)
float scan_data[SCAN_DATA_LENGTH];
uint32_t scan_data_idx = 0;

// HTML Page (same as original, not repeated here for brevity)
const char index_html[] PROGMEM = R"=====( 
<!DOCTYPE html>
<html>
<head>
  <title>LIDAR Visualization</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background-color: #f0f0f0; }
    .container { max-width: 700px; margin: 0 auto; background-color: white; padding: 20px; border-radius: 10px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
    h1 { color: #333; text-align: center; }
    canvas { display: block; margin: 20px auto; border: 1px solid #ddd; border-radius: 5px; }
    button { background-color: #4CAF50; border: none; color: white; padding: 10px 20px; font-size: 16px; margin: 10px 0; cursor: pointer; border-radius: 5px; }
    button:hover { background-color: #45a049; }
    #scanFreq { text-align: center; font-size: 18px; margin-top: 10px; font-weight: bold; }
  </style>
</head>
<body>
<div class="container">
  <h1>ESP32 LIDAR Visualization</h1>
  <canvas id="myCanvas" width="640" height="640"></canvas>
  <div style="text-align: center;">
    <button onclick="start()">Start Visualization</button>
  </div>
  <div id="scanFreq"></div>
</div>
<script>
const start = () => {
  const max_dist = 8000;
  const canvas = document.getElementById("myCanvas");
  const freqDiv = document.getElementById("scanFreq");
  const ctx = canvas.getContext("2d");

  ctx.fillStyle = "red";
  var host = (location.protocol === 'https:' ? 'wss://' : 'ws://') + window.location.hostname + ':81';
  var socket = new WebSocket(host);
  socket.binaryType = 'arraybuffer';

  var pts = [];
  var canvas_draw = document.createElement('canvas');
  canvas_draw.width = canvas.width;
  canvas_draw.height = canvas.height;
  var context_draw = canvas_draw.getContext('2d');
  var last_ts = Date.now();

  freqDiv.innerHTML = 'Connecting...';

  socket.onopen = () => {
    freqDiv.innerHTML = 'Connected! Waiting for data...';
  };

  socket.onerror = (error) => {
    freqDiv.innerHTML = 'WebSocket Error!';
    console.error('WebSocket Error:', error);
  };

  socket.onclose = () => {
    freqDiv.innerHTML = 'Connection closed';
  };

  socket.onmessage = (msg) => {
    try {
      const dot_array = new Float32Array(msg.data);
      for (let i = 0; i < dot_array.length; i += 3) {
        const pcm = dot_array.slice(i, i + 3);
        if (pcm[2] > 100 && pcm[1] > 100 && pcm[1] < max_dist) {
          const x_scale = canvas.width / max_dist;
          const y_scale = canvas.height / max_dist;
          const x = canvas.width / 2 - pcm[1] * x_scale * Math.sin(pcm[0] * Math.PI / 180.0);
          const y = canvas.height / 2 - pcm[1] * y_scale * Math.cos(pcm[0] * Math.PI / 180.0);
          pts.push({ a: pcm[0], x: x, y: y });
        }
      }

      context_draw.fillStyle = "#f8f8f8";
      context_draw.fillRect(0, 0, canvas_draw.width, canvas_draw.height);

      context_draw.fillStyle = "blue";
      context_draw.beginPath();
      context_draw.arc(canvas.width / 2, canvas.height / 2, 5, 0, 2 * Math.PI);
      context_draw.fill();

      context_draw.fillStyle = "red";
      for (let pt of pts) {
        context_draw.fillRect(pt.x, pt.y, 3, 3);
      }

      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(canvas_draw, 0, 0);
      pts = [];

      const ts = Date.now();
      const diff = ts - last_ts;
      last_ts = ts;
      const freq = 1 / (diff / 1000.);
      freqDiv.innerHTML = 'Scan frequency: ' + freq.toFixed(2) + ' Hz';
    } catch (e) {
      console.error(`Error: ${e}`);
    }
  };
};
</script>
</body>
</html>
)=====";

typedef enum coin_d4_read_state {
  READ_SYNC,
  READ_HEADER,
  READ_PACKETS,
} coin_d4_read_state;

class CoinD4 {
public:
  static constexpr uint8_t start_lidar[4] = { 0xAA, 0x55, 0xF0, 0x0F };
  static constexpr uint8_t end_lidar[4] = { 0xAA, 0x55, 0xF5, 0x0A };
  static constexpr uint8_t high_speed[4] = { 0xAA, 0x55, 0xF2, 0x0D };
  typedef void (*ScanPointCallback)(float, float, float, bool);

private:
  HardwareSerial* intf;
  coin_d4_read_state current_state;
  uint8_t rx_buffer[256];
  uint16_t packet_buffer_to_read;
  uint16_t rx_buffer_write_index;
  uint16_t checksum_calc;
  uint16_t checksum;
  uint8_t nb_samples;
  uint16_t start_angle, end_angle;
  float start_angle_f, end_angle_f, angle_interval, rate;
  bool one_turn;
  uint8_t scan_freq;
  long long last_start;

public:
  CoinD4(HardwareSerial* intf) : intf(intf), current_state(READ_SYNC), last_start(0) {}

  void begin() {
    this->intf->begin(230400);
  }

  void start() {
    this->intf->write(start_lidar, 4);
    this->intf->flush();
    delay(200);
    this->intf->write(high_speed, 4);
    this->intf->flush();
  }

  void stop() {
    this->intf->write(end_lidar, 4);
    this->intf->flush();
    delay(200);
  }

  int loop() {
    int actual_read, to_read, serial_available = 0;
    bool packet_processed = false;

    while ((serial_available = this->intf->available()) > 0 && !packet_processed) {
      switch (this->current_state) {
        case READ_SYNC:
          this->one_turn = false;
          if (serial_available >= 2) {
            uint8_t aa = this->intf->read();
            if (0xAA == aa && 0x55 == this->intf->read()) {
              this->current_state = READ_HEADER;
              this->checksum_calc = 0x55AA;
            }
          }
          break;

        case READ_HEADER:
          if (serial_available >= 8) {
            this->intf->readBytes(this->rx_buffer, 8);
            this->nb_samples = this->rx_buffer[1];
            this->start_angle = (this->rx_buffer[2] + (this->rx_buffer[3] << 8)) >> 1;
            this->end_angle = (this->rx_buffer[4] + (this->rx_buffer[5] << 8)) >> 1;
            this->checksum = (this->rx_buffer[6] + (this->rx_buffer[7] << 8));

            for(int i = 0; i < 3; i++) {
              this->checksum_calc ^= this->rx_buffer[i*2] + (this->rx_buffer[i*2 + 1] << 8);
            }

            this->start_angle_f = ((float)this->start_angle) / 64.f;
            this->end_angle_f = ((float)this->end_angle) / 64.f;
            if (this->end_angle_f < this->start_angle_f) this->end_angle_f += 360;
            this->angle_interval = (this->nb_samples == 1) ? 0 : (this->end_angle_f - this->start_angle_f) / (this->nb_samples - 1);
            this->packet_buffer_to_read = this->nb_samples * 3;
            this->rx_buffer_write_index = 0;
            this->current_state = (this->packet_buffer_to_read <= 256) ? READ_PACKETS : READ_SYNC;
          }
          break;

        case READ_PACKETS:
          to_read = min(this->packet_buffer_to_read, (uint16_t)serial_available);
          if (to_read > 0) {
            actual_read = this->intf->readBytes(&this->rx_buffer[this->rx_buffer_write_index], to_read);
            if (actual_read > 0) {
              this->rx_buffer_write_index += actual_read;
              this->packet_buffer_to_read -= actual_read;
            }
          }

          if (this->packet_buffer_to_read == 0) {
            uint16_t val = 0;
            for (size_t pos = 0; pos < (this->nb_samples * 3); ++pos) {
              if (pos % 3 == 2) {
                val += this->rx_buffer[pos] << 8;
                this->checksum_calc ^= val;
              } else if (pos % 3 == 1) {
                val = this->rx_buffer[pos];
              } else {
                val = this->rx_buffer[pos];
                this->checksum_calc ^= this->rx_buffer[pos];
              }
            }

            if (this->checksum_calc == this->checksum) {
              for (int i = 0; i < this->nb_samples; i++) {
                float angle = this->start_angle_f + this->angle_interval * i;
                uint16_t distance = this->rx_buffer[i * 3] | (this->rx_buffer[i * 3 + 1] << 8);
                uint8_t quality = this->rx_buffer[i * 3 + 2];
                if (scan_data_idx < SCAN_DATA_LENGTH - 3) {
                  scan_data[scan_data_idx++] = angle;
                  scan_data[scan_data_idx++] = distance;
                  scan_data[scan_data_idx++] = quality;
                  if (scan_data_idx >= SCAN_DATA_LENGTH - 3 || (this->one_turn && i == this->nb_samples - 1)) {
                    webSocket.broadcastBIN((uint8_t*)scan_data, scan_data_idx * sizeof(float));
                    scan_data_idx = 0;
                    packet_processed = true;
                  }
                }
              }
            }
            this->current_state = READ_SYNC;
          }
          break;
      }
    }
    return 0;
  }

  float getRate() { return this->rate; }
};

CoinD4 lidar(&Serial1);

void webSocketEvent(uint8_t num, WStype_t type, uint8_t *payload, size_t length) {
  if (type == WStype_CONNECTED) {
    IPAddress ip = webSocket.remoteIP(num);
    Serial.printf("[%u] Connected from %d.%d.%d.%d\n", num, ip[0], ip[1], ip[2], ip[3]);
  } else if (type == WStype_DISCONNECTED) {
    Serial.printf("[%u] Disconnected!\n", num);
  }
}

void setup() {
  Serial.begin(115200);
  delay(1000);

  // Start WiFi Access Point
  WiFi.softAP(AP_SSID, AP_PASSWORD);
  delay(1000);

  Serial.print("Access Point started with IP: ");
  Serial.println(WiFi.softAPIP());

  server.begin();
  webSocket.begin();
  webSocket.onEvent(webSocketEvent);

  // Send web page when client connects
  Serial1.begin(230400);
  lidar.begin();
  lidar.start();
}

void loop() {
  webSocket.loop();
  WiFiClient client = server.available();

  if (client) {
    Serial.println("New Client.");
    String request = client.readStringUntil('\r');
    client.flush();
    if (request.indexOf("GET") >= 0) {
      client.print("HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n");
      client.print(index_html);
    }
    delay(1);
    client.stop();
  }

  lidar.loop();
}
```

Maybe you can guide me through this problem,
Thanks in advance,
Nayel

**Comment by jpiat** [comment]
Hi,

i haven't tested on esp32 yet but will give it a try soon. If the LIDAR does not start spinning its because sending the start command failed. If you look at what is going on on TX of the serial interface, do you see the start command being sent ? Are you sure that you are on the correct serial interface ? Are you also sure that you wired TX from the ESP32 to RX of LIDAR (and RX of ESP32 to TX of lidar  ?

Regards,

**Comment by jpiat** [comment]
Here is an example code tested wth ESP32-S3 (no Wifi, just checks that the LIDAR turns and spits data out) using Serial0 to interface. I pushed some changes in the last commit to have HardwareSerial instead of UART for the interface.

```
#include "coin_d4.hpp"

#define SCAN_DATA_LENGTH (512 * 3)
float scan_data[SCAN_DATA_LENGTH];
uint32_t scan_data_idx = 0;
void scan_point_callback(float angle_deg, float distance_m, float quality,
                         bool scan_completed) {
  static int i = 0;
  float data_array[3] = { angle_deg, distance_m, quality };
  if (scan_data_idx < SCAN_DATA_LENGTH) {
    scan_data[scan_data_idx++] = angle_deg;
    scan_data[scan_data_idx++] = distance_m * 1000.f;
    scan_data[scan_data_idx++] = quality;
  }
  if (scan_completed) {
    scan_data_idx = 0;
  }
  if (scan_completed) {
    Serial.print(i);
    Serial.print(' ');
    Serial.print(distance_m * 1000);
    Serial.print(' ');
    Serial.print(angle_deg);
    if (scan_completed)
      Serial.println('*');
    else
      Serial.println();
  }
}



CoinD4 lidar(&Serial0);

void setup() {

  Serial.begin(115200);

  lidar.setScanPointCallback(scan_point_callback);
  lidar.begin();
  lidar.stop();
  delay(1000);
  lidar.start();
}

long long last_packet = 0;
void loop() {
  long long now = millis();
  int ret = lidar.loop();
  delay(5);
}
```

**Comment by Nacros115** [comment]
Hello,

I tried swapping the RX and TX lines, but still no luck. I also monitored the LiDAR's output using Sigrok, with the LiDAR powered only by the power supply shown in the photo—no MCU was connected. It does draw some current, so it's clearly doing something, but I can't get it to spin or produce any output.

I also tested your code using the ESP32 FireBeetle 2 (I don't have an ESP32-S2), but still got no response. I tried several baud rates—38400, 115200, and 230400—with no success. The small LED inside the LiDAR does light up occasionally, but otherwise, nothing useful happens.

I'll try again with a different MCU, but for now, nothing seems to be working.

Thanks in advance,
Best Regards,
Nayel
![Image](https://github.com/user-attachments/assets/a9c6c032-ae40-4e54-af2a-5333d09df810)

![Image](https://github.com/user-attachments/assets/1d5583ad-1b0a-482b-9bf2-392ed03a1866)

![Image](https://github.com/user-attachments/assets/d62a5b17-7fe1-4681-9bee-9fba23da0dae)

![Image](https://github.com/user-attachments/assets/179fdae1-6ff3-4116-ab2e-769087793bb7)

**Comment by jpiat** [comment]
If you rotate/shake the lidar left and right, the blue led should blink and you should see some output on serial. On your picture i don't see a common ground with the esp32 ?  Your two dupont  wire don't short by touching each other ? The 1W power consumption seems very high for a lidar that does not rotate ...

**Comment by Nacros115** [comment]
Hello again,
I finally got the LIDAR working with the STM Nucleo-U083RC board after making some additional code adjustments. While the LIDAR is now operational, the output data isn't very comprehensible, which I believe is due to issues in my code.

```
#include "coin_d4.hpp"

// Define LIDAR UART pins for the STM32U083RC
// Assuming we're using UART1 (PA9/PA10) for the LIDAR
// Check pinout for your specific board configuration
#if defined(ARDUINO_NUCLEO_U083RC)
HardwareSerial Serial1(PA10, PA9); // RX, TX
#define LIDAR_SERIAL Serial1
#else
#define LIDAR_SERIAL Serial0
#endif

#define SCAN_DATA_LENGTH (512 * 3)
float scan_data[SCAN_DATA_LENGTH];
uint32_t scan_data_idx = 0;

void scan_point_callback(float angle_deg, float distance_m, float quality, bool scan_completed) {
  static int i = 0;
  
  if (scan_data_idx < SCAN_DATA_LENGTH) {
    scan_data[scan_data_idx++] = angle_deg;
    scan_data[scan_data_idx++] = distance_m * 1000.0f;
    scan_data[scan_data_idx++] = quality;
  }
  
  if (scan_completed) {
    scan_data_idx = 0;
    i++;
  }
  
  if (scan_completed) {
    Serial.print(i);
    Serial.print(' ');
    Serial.print(distance_m * 1000);
    Serial.print(' ');
    Serial.print(angle_deg);
    if (scan_completed)
      Serial.println('*');
    else
      Serial.println();
  }
}

CoinD4 lidar(&LIDAR_SERIAL);

void setup() {
  // Initialize debug serial port
  Serial.begin(115200);
  while (!Serial && millis() < 3000); // Wait for serial port to connect (max 3 seconds)
  
  Serial.println("STM32U083RC LIDAR Initialization");
  
  // Initialize LIDAR
  lidar.setScanPointCallback(scan_point_callback);
  lidar.begin();
  lidar.stop();
  delay(1000);
  lidar.start();
  
  Serial.println("LIDAR Started");
}

unsigned long last_packet = 0;

void loop() {
  unsigned long now = millis();
  int ret = lidar.loop();
  
  // Optional - print scan frequency every second
  if (now - last_packet > 1000) {
    Serial.print("Scan freq: ");
    Serial.print(lidar.getScanFreqHz());
    Serial.println(" Hz");
    last_packet = now;
  }
  
  delay(5);
}

```

Here is the coin_d4.hpp :

```
#pragma once
#include <Arduino.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>

// Define serial interface for STM32 Nucleo U083RC
#if !defined(Serial0) && defined(USART1)
#define Serial0 Serial1
#endif

typedef enum coin_d4_read_state {
  READ_SYNC,
  READ_HEADER,
  READ_PACKETS,
} coin_d4_read_state;

class CoinD4 {
public:
  static constexpr uint8_t start_lidar[4] = { 0xAA, 0x55, 0xF0, 0x0F };
  static constexpr uint8_t end_lidar[4] = { 0xAA, 0x55, 0xF5, 0x0A };
  static constexpr uint8_t low_exposure[4] = { 0xAA, 0x55, 0xF1, 0x0E };
  static constexpr uint8_t high_exposure[4] = { 0xAA, 0x55, 0xF2, 0x0D };
  static constexpr uint8_t get_version[4] = { 0xAA, 0x55, 0xFC, 0x03 };
  static constexpr uint8_t high_speed[4] = { 0xAA, 0x55, 0xF2, 0x0D };
  static constexpr uint8_t low_speed[4] = { 0xAA, 0x55, 0xF1, 0x0E };
  typedef void (*ScanPointCallback)(float, float, float, bool);

public:
  CoinD4(HardwareSerial* intf);
  void begin();
  void init();
  void start();
  void stop();
  int loop();

  void setScanPointCallback(ScanPointCallback scan_callback);
  float getScanFreqHz();

protected:
  HardwareSerial* intf;
  uint8_t rx_buffer[256];
  uint8_t rx_buffer_write_index = 0;
  ScanPointCallback scan_point_callback;
  coin_d4_read_state current_state;
  uint16_t packet_buffer_to_read;
  uint16_t nb_samples = 0;
  uint16_t start_angle = 0;
  uint16_t end_angle = 0;
  uint16_t checksum = 0;
  uint16_t checksum_calc = 0;
  float angle_interval;
  float angle_interval_last_package;
  uint8_t scan_freq = 0;
  unsigned long last_start = 0; // Changed to unsigned long for Arduino compatibility
  float rate = -1; 
  bool one_turn;
  float start_angle_f, end_angle_f;
};
```
And finnally the coin_d4.cpp : 

```
#include "coin_d4.hpp"

CoinD4::CoinD4(HardwareSerial* intf) {
  this->intf = intf;
  this->current_state = READ_SYNC;
}

void CoinD4::begin() {
  this->intf->begin(230400);
}

void CoinD4::start() {
  this->intf->write(CoinD4::start_lidar, 4);
  this->intf->flush();
  delay(200);
  this->intf->write(CoinD4::high_speed, 4);
  this->intf->flush();
}

void CoinD4::stop() {
  this->intf->write(CoinD4::end_lidar, 4);
  this->intf->flush();
  delay(200);
}

int CoinD4::loop() {
  int ret = 0;
  int actual_read;
  int to_read;
  int serial_available = 0;
  bool packet_processed = false;
  
  while ((serial_available = this->intf->available()) > 0 && !packet_processed) {
    switch (this->current_state) {
      case READ_SYNC:
        this->one_turn = false;
        if (serial_available >= 2) {
          uint8_t aa = this->intf->read();
          if (0xAA == aa) {
            uint8_t cc = this->intf->read();
            if (cc == 0x55) {
              this->current_state = READ_HEADER;
              this->checksum_calc = 0x55AA;
            }
          }
        }
        break;
        
      case READ_HEADER:
        if (serial_available >= 8) {
          this->intf->readBytes(this->rx_buffer, 8);
          if ((this->rx_buffer[0] & 0x01) == 1) {
            // RING START, can be used to compute scan duration
            unsigned long now = millis();
            unsigned long diff = now - last_start;
            last_start = now;
            this->rate = 1000.0f / (float)(diff);
            this->scan_freq = (this->rx_buffer[0] & 0xFE) >> 1;
            this->one_turn = true;
          }
          
          for(int i = 0; i < 3; i++) {
            this->checksum_calc ^= this->rx_buffer[i*2] + (this->rx_buffer[i*2 + 1] << 8);
          }

          this->nb_samples = this->rx_buffer[1];
          this->start_angle = (this->rx_buffer[2] + (this->rx_buffer[3] << 8));
          if ((this->start_angle & 0x01) == 0) {
            this->current_state = READ_SYNC;
            break;
          }
          
          this->start_angle = this->start_angle >> 1;
          this->end_angle = (this->rx_buffer[4] + (this->rx_buffer[5] << 8));
          if ((this->end_angle & 0x01) == 0) {
            this->current_state = READ_SYNC;
            break;
          }
          
          this->end_angle = this->end_angle >> 1;
          this->checksum = (this->rx_buffer[6] + (this->rx_buffer[7] << 8));  // Need to check checksum
          this->packet_buffer_to_read = nb_samples * 3;
          this->start_angle_f = ((float)start_angle) / 64.0f;
          this->end_angle_f = ((float)end_angle) / 64.0f;
          
          if (nb_samples == 1) {
            this->angle_interval = 0;
          } else {
            if (end_angle_f < start_angle_f) {
              this->end_angle_f += 360.0f;
            }
            this->angle_interval = (this->end_angle_f - this->start_angle_f) / (this->nb_samples - 1);
          }
          
          this->rx_buffer_write_index = 0;
          if (this->packet_buffer_to_read <= 256) {
            this->rx_buffer_write_index = 0;
            this->current_state = READ_PACKETS;
          } else {
            this->current_state = READ_SYNC;
          }
        }
        break;
        
      case READ_PACKETS:
        to_read = this->packet_buffer_to_read;
        if (to_read > serial_available) {
          to_read = serial_available;
        }
        if (to_read == 0 && this->packet_buffer_to_read <= 0) {
          this->current_state = READ_SYNC;
        }
        if (to_read > 0) {
          actual_read = this->intf->readBytes(&this->rx_buffer[this->rx_buffer_write_index], to_read);
          if (actual_read > 0) {
            this->rx_buffer_write_index += actual_read;
            this->packet_buffer_to_read -= actual_read;
          }
        }
        
        if (this->packet_buffer_to_read == 0) {
          uint16_t Valu8Tou16 = 0;
          for (size_t pos = 0; pos < (this->nb_samples * 3); ++pos) {
            if (pos % 3 == 2) {
              Valu8Tou16 += rx_buffer[pos] << 8;
              this->checksum_calc ^= Valu8Tou16;
            } else if (pos % 3 == 1) {
              Valu8Tou16 = rx_buffer[pos];
            } else {
              Valu8Tou16 = rx_buffer[pos];
              this->checksum_calc ^= rx_buffer[pos];
            }
          }
          
          if (this->checksum_calc == this->checksum) {
            for (int i = 0; i < nb_samples; i++) {
              uint16_t distance = (rx_buffer[i * 3 + 2] << 6) + (rx_buffer[i * 3 + 1] >> 2);
              uint16_t quality = (rx_buffer[i * 3] >> 2) + ((rx_buffer[i * 3 + 1] & 0x03) << 6);
              uint16_t exp = rx_buffer[i * 3] & 0x01;  // Not sure what it can be used for...

              float distance_m_f = ((float)distance) / 1000.0f;
              float angle_correction = 0;
              if (distance > 0) {
                angle_correction = (float)(atan(19.16 * (distance - 90.15) / (90.15 * distance)));
              }
              float angle_deg_f = (start_angle_f + (i * angle_interval) + angle_correction);
              angle_deg_f = angle_deg_f >= 360.0f ? (angle_deg_f - 360.0f) : angle_deg_f;
              this->scan_point_callback(angle_deg_f, distance_m_f, (float)quality, this->one_turn);
            }
            ret = 1;
            this->current_state = READ_SYNC;
            packet_processed = true;
          } else {
            // Removed the debug print statements to avoid Serial conflict
            this->current_state = READ_SYNC;
            ret = 0;
          }
        }
        break;
        
      default:
        this->current_state = READ_SYNC;
        break;
    }
  }
  return ret;
}

void CoinD4::setScanPointCallback(ScanPointCallback scan_callback) {
  this->scan_point_callback = scan_callback;
}

float CoinD4::getScanFreqHz() {
  return this->rate;
}

```
Here is a video of the lidar : 

 
https://github.com/user-attachments/assets/0f4bbd68-0c94-486d-8fbc-ba9a03084ebc

**Comment by Nacros115** [comment]
> If you rotate/shake the lidar left and right, the blue led should blink and you should see some output on serial. On your picture i don't see a common ground with the esp32 ? Your two dupont wire don't short by touching each other ? The 1W power consumption seems very high for a lidar that does not rotate ...

Yes indeed. When I slightly shake the LIDAR, the LED blinks, but I'm not seeing any data output. I realized I forgot to connect a common ground between the microcontroller and the LIDAR. There isn't a ground wire visible in the video, so I'll add one right away. I was very careful with the two Dupont connectors so they wouldn't touch each other.

**Comment by jpiat** [comment]
For the ESP32, could your try the exact same code that is on the repository with just changing the SerialX interface to match the one you use and the WiFi related parameters ? You can power the Lidar through the 5v/VCC + GND pins of the firebeetle to avoid any power supply wiring issue.

**Comment by jpiat** [comment]
On other thing. On the firebeetle RX/TX pins are also wired to the onboard USB to serial adapter so you should not use those pins to connect the LIDAR ... Try using any other set of pins and the Serial1 interface (that you can configure to use almost any pin).

**Comment by jpiat** [comment]
I just pushed a change that should allow ot select different pins. Just have a look at the ino file and define your RX/TX pins at the top

**Comment by Nacros115** [comment]
I was wondering wich version of the WebSocketsServer  are you using ? Because I'm getting this error : 

![Image](https://github.com/user-attachments/assets/b604c884-a64c-475d-99c2-6378330efe2f)

**Comment by Nacros115** [comment]
https://github.com/user-attachments/assets/8d56a0a6-85e9-4978-89f5-edaf4dc86928

After encountering this error, I made changes to the main code, and here is the updated result:

```#include "coin_d4.hpp"
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <WebSocketsServer_Generic.h>

#define LIDAR_RX 25
#define LIDAR_TX 26

#define SSID "Bbox-E19DB58B"
#define PASSWORD "Sb24DV2nVZHd7zHZsN"

WiFiServer server(80);
WebSocketsServer webSocket = WebSocketsServer(81);

// Define the HTML content for the web page directly
const char index_html[] PROGMEM = R"rawliteral(
<!DOCTYPE HTML>
<html>
<head>
  <title>LIDAR Visualization</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: Arial; text-align: center; margin:0px auto; padding-top: 30px;}
    .container { width: 100%; max-width: 800px; margin: 0 auto; }
    #lidarCanvas { border: 1px solid #ddd; background-color: #f8f8f8; }
  </style>
</head>
<body>
  <div class="container">
    <h2>LIDAR Visualization</h2>
    <canvas id="lidarCanvas" width="800" height="800"></canvas>
  </div>
  
  <script>
    var webSocket;
    var canvas = document.getElementById("lidarCanvas");
    var ctx = canvas.getContext("2d");
    
    function initWebSocket() {
      const wsProtocol = window.location.protocol === 'https:' ? 'wss://' : 'ws://';
      const wsUrl = wsProtocol + window.location.hostname + ':81/';
      console.log('Connecting to: ' + wsUrl);
      
      webSocket = new WebSocket(wsUrl);
      webSocket.binaryType = "arraybuffer";
      
      webSocket.onopen = function(evt) {
        console.log("WebSocket connected");
      };
      
      webSocket.onclose = function(evt) {
        console.log("WebSocket disconnected");
        setTimeout(initWebSocket, 2000);
      };
      
      webSocket.onmessage = function(evt) {
        if (evt.data instanceof ArrayBuffer) {
          const floatArray = new Float32Array(evt.data);
          drawLidarData(floatArray);
        }
      };
      
      webSocket.onerror = function(evt) {
        console.log("WebSocket error: " + evt);
      };
    }
    
    function drawLidarData(data) {
      const centerX = canvas.width / 2;
      const centerY = canvas.height / 2;
      const scale = Math.min(centerX, centerY) * 0.8;
      
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      
      // Draw a circle indicating the LIDAR position
      ctx.beginPath();
      ctx.arc(centerX, centerY, 10, 0, 2 * Math.PI);
      ctx.fillStyle = 'blue';
      ctx.fill();
      
      // Draw concentric circles for distance reference
      ctx.strokeStyle = '#ddd';
      ctx.beginPath();
      for (let r = 500; r <= 2000; r += 500) {
        const radius = (r / 2000) * scale;
        ctx.arc(centerX, centerY, radius, 0, 2 * Math.PI);
      }
      ctx.stroke();
      
      // Draw the LIDAR data points
      for (let i = 0; i < data.length; i += 3) {
        const angle = data[i]; // Angle in degrees
        const distance = data[i + 1]; // Distance in mm
        const quality = data[i + 2]; // Quality
        
        if (distance > 0 && quality > 0) {
          const angleRad = (angle - 90) * Math.PI / 180; // Convert to radians, -90 to rotate
          const x = centerX + Math.cos(angleRad) * (distance / 2000) * scale;
          const y = centerY + Math.sin(angleRad) * (distance / 2000) * scale;
          
          ctx.beginPath();
          ctx.arc(x, y, 2, 0, 2 * Math.PI);
          
          // Color based on quality (red to green)
          const hue = Math.min(quality / 2, 120); // Map quality to 0-120 (red to green)
          ctx.fillStyle = `hsl(${hue}, 100%, 50%)`;
          ctx.fill();
        }
      }
    }
    
    window.onload = function() {
      initWebSocket();
    };
  </script>
</body>
</html>
)rawliteral";

#define SCAN_DATA_LENGTH (512 * 3)
float scan_data[SCAN_DATA_LENGTH];
uint32_t scan_data_idx = 0;

void webSocketEvent(uint8_t num, WStype_t type, uint8_t *payload, size_t length);

void scan_point_callback(float angle_deg, float distance_m, float quality,
                         bool scan_completed) {
  if (scan_data_idx < SCAN_DATA_LENGTH) {
    scan_data[scan_data_idx++] = angle_deg;
    scan_data[scan_data_idx++] = distance_m * 1000.f;
    scan_data[scan_data_idx++] = quality;
  }
  
  if (scan_completed) {
    webSocket.broadcastBIN((uint8_t *)scan_data, scan_data_idx * sizeof(float));
    scan_data_idx = 0;
  }
}

CoinD4 lidar(&Serial1);
bool connected = false;
unsigned long lastConnectionAttempt = 0;
const unsigned long connectionRetryInterval = 30000; // 30 seconds

void setup() {
  Serial.begin(115200);
  
  // Initialize WiFi
  WiFi.mode(WIFI_STA);
  WiFi.setHostname("coin-lidar");
  connectToWiFi();
  
  // Initialize HTTP server and WebSocket server
  server.begin();
  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
  
  // Initialize LIDAR
  lidar.setScanPointCallback(scan_point_callback);
#if defined(LIDAR_RX) && defined(LIDAR_TX)
  lidar.begin(LIDAR_RX, LIDAR_TX);
#else
  lidar.begin();
#endif
  lidar.stop();
  delay(1000);
  lidar.start();
}

void connectToWiFi() {
  Serial.printf("Connecting to '%s'\n", SSID);
  WiFi.begin(SSID, PASSWORD);
  
  // Wait up to 20 seconds for connection
  int timeout = 0;
  while (WiFi.status() != WL_CONNECTED && timeout < 200) {
    delay(100);
    Serial.print(".");
    timeout++;
  }
  
  if (WiFi.status() == WL_CONNECTED) {
    Serial.println("\nConnected!");
    Serial.print("IP address: ");
    Serial.println(WiFi.localIP());
  } else {
    Serial.println("\nFailed to connect. Will retry later.");
  }
  
  lastConnectionAttempt = millis();
}

void webSocketEvent(uint8_t num, WStype_t type, uint8_t *payload, size_t length) {
  switch (type) {
    case WStype_DISCONNECTED:
      Serial.printf("[%u] Disconnected!\n", num);
      break;
      
    case WStype_CONNECTED: {
      IPAddress ip = webSocket.remoteIP(num);
      Serial.printf("[%u] Connected from %d.%d.%d.%d url: %s\n", num, 
                   ip[0], ip[1], ip[2], ip[3], payload);
      connected = true;
      break;
    }
    
    case WStype_TEXT:
      // Handle text commands from client (if needed)
      Serial.printf("[%u] Received text: %s\n", num, payload);
      break;
      
    case WStype_BIN:
      // Handle binary data from client (if needed)
      Serial.printf("[%u] Received binary data\n", num);
      break;
      
    case WStype_ERROR:
      Serial.printf("[%u] Error occurred\n", num);
      break;
      
    case WStype_FRAGMENT_TEXT_START:
    case WStype_FRAGMENT_BIN_START:
    case WStype_FRAGMENT:
    case WStype_FRAGMENT_FIN:
      // These are for handling fragmented messages
      break;
  }
}

void handleHTTPClient() {
  WiFiClient client = server.available();
  
  if (client) {
    Serial.println("New HTTP client");
    unsigned long timeout = millis();
    
    // Wait for data from client with timeout
    while (client.connected() && !client.available()) {
      if (millis() - timeout > 1000) {
        Serial.println("HTTP client timeout");
        client.stop();
        return;
      }
      delay(1);
    }
    
    // Read the first line of the request
    String request = client.readStringUntil('\r');
    Serial.println("Request: " + request);
    client.flush();
    
    // Send the response
    client.println("HTTP/1.1 200 OK");
    client.println("Content-Type: text/html");
    client.println("Connection: close");
    client.println();
    client.print(index_html);
    
    // Give time for the data to be sent
    delay(10);
    client.stop();
    Serial.println("HTTP client disconnected");
  }
}

unsigned long lastPacketTime = 0;
void loop() {
  unsigned long currentTime = millis();
  
  // Check WiFi connection and reconnect if needed
  if (WiFi.status() != WL_CONNECTED) {
    if (currentTime - lastConnectionAttempt > connectionRetryInterval) {
      Serial.println("WiFi connection lost. Reconnecting...");
      connectToWiFi();
    }
  } else {
    // Process WebSocket events and HTTP requests
    webSocket.loop();
    handleHTTPClient();
  }
  
  // Handle LIDAR data
  int ret = lidar.loop();
  if (ret) {
    lastPacketTime = currentTime;
  }
  
  // Restart LIDAR if no data received for 5 seconds
  if ((currentTime - lastPacketTime) > 5000) {
    Serial.println("No LIDAR data for 5 seconds, restarting LIDAR");
    lidar.stop();
    delay(1000);
    lidar.start();
    lastPacketTime = currentTime;
  }
  
  // Small delay to prevent CPU hogging
  delay(1);
}```

https://github.com/user-attachments/assets/fae9438c-377a-4fba-a5c3-bdc26eedadd0

**Comment by jpiat** [comment]
Hi, the websocket library i used is [https://github.com/Links2004/arduinoWebSockets](url). Glad to see that its working now !
